### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by zhitkovk** [yurap/homeseek#12]
Привет,

Не слишком технический комментарий, но возможно будет полезно.

Когда я хочу снять жильё, мне больше всего интересны фильтры, хочется чтобы на главной странице можно было сразу выбрать метро, цену, расстояние до метро, посмотреть на карте, убрать объявления без фото и т.д. Как потенциального арендатора меня не очень интересует количество объявлений по веткам метро или группам. Такая информация скорее будет полезна тем, кто хочет сдать квартиру, чтобы оценить рынок. Если человек заметит, что где-то сдают совсем мало квартир, то он сможет поставить цену выше или же наоборот снизить, если ему нужно сдать максимально быстро. В общем в идеале бы иметь сверху какой-нибудь переключатель: информация для арендаторов/информация для арендодателей. Ещё одной полезной фичей для арендодателей было бы время, которое объявление висело в группе до момента сдачи квартиры (не для всех квартир люди пишут в комментах снизу, что предложение ушло, но можно попробовать). 

P.S. Классная идея собирать все эти данные в одном месте.

**Comment by yurap** [comment]
Привет!

Сейчас про каждую группу я спрашиваю только свежайшие 100 постов, и если какой-то протух, то сервис не знает про это. Отчасти поэтому из объявлений вырезаются телефоны, чтобы вынудить перед звонком человека пройти к оригинальному источнику и увидеть, что пост удален.

Было бы лучше, конечно, про каждый пост регулярно опрашивать состояние, но это увеличит число запросов и вообще сложнее в реализации, поэтому пока отложил.

Фича про время для арендодателей, получается, ложится в этот же долгий ящик.

**Comment by yurap** [comment]
А статистику спрятал сейчас вглубь.

**Comment by yurap** [comment]
Спасибо большое! Обратная связь очень важна для меня, особенно, конструктивная)
